import type { Metadata } from "next";
import "./globals.css";
import { Inter, Playfair_Display, Space_Grotesk } from "next/font/google";


// app/layout.tsx or wherever you want to use them


const inter = Inter({
  subsets: ["latin"],       // required
  weight: ["400", "500", "600"], // optional
  variable: "--font-inter", // optional CSS variable
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-space-grotesk",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className={`${inter.variable} ${playfair.variable} ${spaceGrotesk.variable}`}>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}

